# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Projects\PA RSCF Popov\PA-RSCF-22-72-00015-\gui\PA_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Data = QtWidgets.QMenu(self.menubar)
        self.menu_Data.setObjectName("menu_Data")
        self.menu_Hardware = QtWidgets.QMenu(self.menubar)
        self.menu_Hardware.setObjectName("menu_Hardware")
        self.menu_Measurements = QtWidgets.QMenu(self.menubar)
        self.menu_Measurements.setObjectName("menu_Measurements")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_New = QtWidgets.QAction(MainWindow)
        self.action_New.setObjectName("action_New")
        self.actionO_pen_recent = QtWidgets.QAction(MainWindow)
        self.actionO_pen_recent.setObjectName("actionO_pen_recent")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.action_Close = QtWidgets.QAction(MainWindow)
        self.action_Close.setObjectName("action_Close")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Init = QtWidgets.QAction(MainWindow)
        self.action_Init.setObjectName("action_Init")
        self.action_Point_measurement = QtWidgets.QAction(MainWindow)
        self.action_Point_measurement.setObjectName("action_Point_measurement")
        self.action_Power_Meter = QtWidgets.QAction(MainWindow)
        self.action_Power_Meter.setObjectName("action_Power_Meter")
        self.menu_Data.addAction(self.action_New)
        self.menu_Data.addAction(self.action_Open)
        self.menu_Data.addAction(self.actionO_pen_recent)
        self.menu_Data.addSeparator()
        self.menu_Data.addAction(self.action_Save)
        self.menu_Data.addAction(self.actionSave_As)
        self.menu_Data.addSeparator()
        self.menu_Data.addAction(self.action_Close)
        self.menu_Data.addSeparator()
        self.menu_Data.addAction(self.action_Exit)
        self.menu_Hardware.addAction(self.action_Init)
        self.menu_Hardware.addSeparator()
        self.menu_Measurements.addAction(self.action_Point_measurement)
        self.menu_Measurements.addSeparator()
        self.menu_Measurements.addAction(self.action_Power_Meter)
        self.menubar.addAction(self.menu_Data.menuAction())
        self.menubar.addAction(self.menu_Hardware.menuAction())
        self.menubar.addAction(self.menu_Measurements.menuAction())
        self.toolBar.addAction(self.action_Init)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_Data.setTitle(_translate("MainWindow", "&Data"))
        self.menu_Hardware.setTitle(_translate("MainWindow", "&Hardware"))
        self.menu_Measurements.setTitle(_translate("MainWindow", "&Measurements"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_New.setText(_translate("MainWindow", "&New"))
        self.actionO_pen_recent.setText(_translate("MainWindow", "O&pen Recent"))
        self.action_Save.setText(_translate("MainWindow", "&Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save &As"))
        self.action_Close.setText(_translate("MainWindow", "&Close"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_Init.setText(_translate("MainWindow", "&Init All"))
        self.action_Point_measurement.setText(_translate("MainWindow", "&Point Measurement"))
        self.action_Power_Meter.setText(_translate("MainWindow", "&Power Meter"))
