hardware:
  oscilloscope:
    channels: !!int 2 #not implemented
  power_meter:
    connected: !!bool True
    connected_chan: !!int 2
    pre_time: !!int 150 # in [us]
    post_time: !!int 2500 # in [us]
  pa_sensor:
    connected: !!bool True
    connected_chan: !!int 1
    damage_thr: !!int 800 # in [uJ]
    pre_time: !!int 100 # in [us]
    post_time: !!int 150 # in [us]
  energy:
    max_filters: !!int 2
  stages:
    axes: !!int 2
  power_control: ['Glan prism', 'Filters']