# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'map_measure_widget.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QSpinBox, QWidget)

from ..widgets import (MplCanvas, QuantSpinBox)
from . import qt_resources_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(924, 639)
        self.btn_start = QPushButton(Form)
        self.btn_start.setObjectName(u"btn_start")
        self.btn_start.setGeometry(QRect(10, 180, 75, 23))
        self.btn_stop = QPushButton(Form)
        self.btn_stop.setObjectName(u"btn_stop")
        self.btn_stop.setGeometry(QRect(250, 180, 75, 23))
        self.le_result = QLineEdit(Form)
        self.le_result.setObjectName(u"le_result")
        self.le_result.setGeometry(QRect(390, 200, 341, 20))
        self.scan = MplCanvas(Form)
        self.scan.setObjectName(u"scan")
        self.scan.setGeometry(QRect(430, 270, 350, 301))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan.sizePolicy().hasHeightForWidth())
        self.scan.setSizePolicy(sizePolicy)
        self.lbl_cur_pos = QLabel(Form)
        self.lbl_cur_pos.setObjectName(u"lbl_cur_pos")
        self.lbl_cur_pos.setGeometry(QRect(100, 60, 97, 20))
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.lbl_cur_pos.sizePolicy().hasHeightForWidth())
        self.lbl_cur_pos.setSizePolicy(sizePolicy1)
        font = QFont()
        font.setBold(True)
        self.lbl_cur_pos.setFont(font)
        self.lbl_cur_pos.setAlignment(Qt.AlignCenter)
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 90, 47, 13))
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(100, 90, 47, 13))
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(170, 90, 47, 13))
        self.sb_x_new_pos = QuantSpinBox(Form)
        self.sb_x_new_pos.setObjectName(u"sb_x_new_pos")
        self.sb_x_new_pos.setGeometry(QRect(10, 120, 74, 20))
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.sb_x_new_pos.sizePolicy().hasHeightForWidth())
        self.sb_x_new_pos.setSizePolicy(sizePolicy2)
        self.sb_x_new_pos.setMinimumSize(QSize(0, 0))
        self.sb_x_new_pos.setDecimals(2)
        self.sb_x_new_pos_2 = QuantSpinBox(Form)
        self.sb_x_new_pos_2.setObjectName(u"sb_x_new_pos_2")
        self.sb_x_new_pos_2.setGeometry(QRect(10, 150, 74, 20))
        sizePolicy2.setHeightForWidth(self.sb_x_new_pos_2.sizePolicy().hasHeightForWidth())
        self.sb_x_new_pos_2.setSizePolicy(sizePolicy2)
        self.sb_x_new_pos_2.setMinimumSize(QSize(0, 0))
        self.sb_x_new_pos_2.setDecimals(2)
        self.sb_x_new_pos_3 = QSpinBox(Form)
        self.sb_x_new_pos_3.setObjectName(u"sb_x_new_pos_3")
        self.sb_x_new_pos_3.setGeometry(QRect(100, 120, 51, 20))
        sizePolicy2.setHeightForWidth(self.sb_x_new_pos_3.sizePolicy().hasHeightForWidth())
        self.sb_x_new_pos_3.setSizePolicy(sizePolicy2)
        self.sb_x_new_pos_3.setMinimumSize(QSize(0, 0))
        self.sb_x_new_pos_4 = QSpinBox(Form)
        self.sb_x_new_pos_4.setObjectName(u"sb_x_new_pos_4")
        self.sb_x_new_pos_4.setGeometry(QRect(100, 150, 51, 20))
        sizePolicy2.setHeightForWidth(self.sb_x_new_pos_4.sizePolicy().hasHeightForWidth())
        self.sb_x_new_pos_4.setSizePolicy(sizePolicy2)
        self.sb_x_new_pos_4.setMinimumSize(QSize(0, 0))
        self.sb_x_new_pos_5 = QuantSpinBox(Form)
        self.sb_x_new_pos_5.setObjectName(u"sb_x_new_pos_5")
        self.sb_x_new_pos_5.setGeometry(QRect(160, 120, 74, 20))
        sizePolicy2.setHeightForWidth(self.sb_x_new_pos_5.sizePolicy().hasHeightForWidth())
        self.sb_x_new_pos_5.setSizePolicy(sizePolicy2)
        self.sb_x_new_pos_5.setMinimumSize(QSize(0, 0))
        self.sb_x_new_pos_5.setDecimals(2)
        self.sb_x_new_pos_6 = QuantSpinBox(Form)
        self.sb_x_new_pos_6.setObjectName(u"sb_x_new_pos_6")
        self.sb_x_new_pos_6.setGeometry(QRect(160, 150, 74, 20))
        sizePolicy2.setHeightForWidth(self.sb_x_new_pos_6.sizePolicy().hasHeightForWidth())
        self.sb_x_new_pos_6.setSizePolicy(sizePolicy2)
        self.sb_x_new_pos_6.setMinimumSize(QSize(0, 0))
        self.sb_x_new_pos_6.setDecimals(2)
        self.btn_start_2 = QPushButton(Form)
        self.btn_start_2.setObjectName(u"btn_start_2")
        self.btn_start_2.setGeometry(QRect(90, 180, 75, 23))
        self.btn_start_3 = QPushButton(Form)
        self.btn_start_3.setObjectName(u"btn_start_3")
        self.btn_start_3.setGeometry(QRect(170, 180, 75, 23))
        self.line = QFrame(Form)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(50, 330, 118, 3))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.lbl_cur_pos_2 = QLabel(Form)
        self.lbl_cur_pos_2.setObjectName(u"lbl_cur_pos_2")
        self.lbl_cur_pos_2.setGeometry(QRect(70, 340, 97, 20))
        sizePolicy1.setHeightForWidth(self.lbl_cur_pos_2.sizePolicy().hasHeightForWidth())
        self.lbl_cur_pos_2.setSizePolicy(sizePolicy1)
        self.lbl_cur_pos_2.setFont(font)
        self.lbl_cur_pos_2.setAlignment(Qt.AlignCenter)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.btn_start.setText(QCoreApplication.translate("Form", u"Start", None))
        self.btn_stop.setText(QCoreApplication.translate("Form", u"Stop", None))
        self.lbl_cur_pos.setText(QCoreApplication.translate("Form", u"Scan Area", None))
        self.label.setText(QCoreApplication.translate("Form", u"Size", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Points", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Step", None))
        self.sb_x_new_pos.setSuffix(QCoreApplication.translate("Form", u" mm", None))
        self.sb_x_new_pos_2.setSuffix(QCoreApplication.translate("Form", u" mm", None))
        self.sb_x_new_pos_5.setSuffix(QCoreApplication.translate("Form", u" mm", None))
        self.sb_x_new_pos_6.setSuffix(QCoreApplication.translate("Form", u" mm", None))
        self.btn_start_2.setText(QCoreApplication.translate("Form", u"Pause", None))
        self.btn_start_3.setText(QCoreApplication.translate("Form", u"Restart", None))
        self.lbl_cur_pos_2.setText(QCoreApplication.translate("Form", u"Parameters", None))
    # retranslateUi

